#!/usr/bin/env bats

############################ DO NOT EDIT THIS FILE #####################################
# File: student_tests.sh
# 
# Add/Edit Student tests in this file
# 
# All tests in this file must pass - it is used as part of grading!
########################################################################################

@test "Check if dsh starts and exits properly" {
    run ./dsh <<EOF
    exit
EOF
    [ "$status" -eq 0 ]
}

@test "Check if ls runs without errors" {
    run ./dsh <<EOF
    ls
EOF
    [ "$status" -eq 0 ]
}

@test "Check echo command output" {
    run ./dsh <<EOF
    echo "Hello, world!"
EOF
    [ "$status" -eq 0 ]
    [ "${lines[0]}" = "Hello, world!" ]
}

@test "Check simple pipeline" {
    run ./dsh <<EOF
    echo "Hello" | grep "H"
EOF
    [ "$status" -eq 0 ]
    [ "${lines[0]}" = "Hello" ]
}

@test "Check double pipe command" {
    run ./dsh <<EOF
    echo "Hello" | grep "H" | wc -c
EOF
    [ "$status" -eq 0 ]
    [ "${lines[0]}" -eq 6 ]
}
